-- Description:
-- >>> Up >>>
CREATE TABLE IF NOT EXISTS `{!!prefix!!}srvc_services` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `sku` varchar(64) DEFAULT NULL,
  `slug` varchar(64) NOT NULL,
  `name` varchar(64) NOT NULL,
  `short_desc` varchar(512) NOT NULL,
  `long_desc` text DEFAULT NULL,
  `category_id` bigint(20) NOT NULL,
  `service_type_id` bigint(20) NOT NULL,
  `complexity_id` bigint(20) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `is_featured` tinyint(1) NOT NULL DEFAULT 0,
  `minimum_quantity` decimal(8,2) unsigned DEFAULT NULL,
  `maximum_quantity` decimal(8,2) unsigned DEFAULT NULL,
  `estimated_hours` decimal(6,2) unsigned DEFAULT NULL,
  `skill_level` enum('entry','intermediate','advanced','expert','specialist') DEFAULT NULL,
  `metadata` json DEFAULT NULL COMMENT 'Additional service configuration properties',
  `version` int(11) NOT NULL DEFAULT 1 COMMENT 'Optimistic locking version',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` datetime DEFAULT NULL,
  `created_by` bigint(20) unsigned NOT NULL,
  `updated_by` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_service__slug` (`slug`),
  UNIQUE KEY `uq_service__sku` (`sku`),
  KEY `idx_service__category_id` (`category_id`),
  KEY `idx_service__service_type_id` (`service_type_id`),
  KEY `idx_service__complexity_id` (`complexity_id`),
  KEY `idx_service__is_active` (`is_active`),
  KEY `idx_service__is_featured` (`is_featured`),
  KEY `idx_service__deleted_at` (`deleted_at`),
  KEY `idx_service__created_by` (`created_by`),
  KEY `idx_service__updated_by` (`updated_by`),
  KEY `idx_service__sku` (`sku`),
  KEY `idx_service__slug` (`slug`),
  KEY `idx_service__active_lookup` (`is_active`, `category_id`, `service_type_id`, `deleted_at`),
  CONSTRAINT `chk_service__positive_min_quantity` CHECK (`minimum_quantity` > 0),
  CONSTRAINT `chk_service__valid_quantity_range` CHECK (`maximum_quantity` IS NULL OR `maximum_quantity` >= `minimum_quantity`),
  CONSTRAINT `chk_service__positive_estimated_hours` CHECK (`estimated_hours` IS NULL OR `estimated_hours` > 0),
  CONSTRAINT `fk_service__category` FOREIGN KEY (`category_id`) REFERENCES `{!!prefix!!}srvc_categories` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_service__complexity` FOREIGN KEY (`complexity_id`) REFERENCES `{!!prefix!!}srvc_complexity_levels` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_service__service_type` FOREIGN KEY (`service_type_id`) REFERENCES `{!!prefix!!}srvc_service_types` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_service__created_by` FOREIGN KEY (`created_by`) REFERENCES `{!!prefix!!}users` (`ID`) ON UPDATE CASCADE,
  CONSTRAINT `fk_service__updated_by` FOREIGN KEY (`updated_by`) REFERENCES `{!!prefix!!}users` (`ID`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Core service catalog with quantity constraints and promoted metadata fields';

-- >>> Down >>>
DROP TABLE IF EXISTS `{!!prefix!!}srvc_services`;